load_defaults: 8.0.1
development:
  adapter: solr
  url: <%= ENV['YCBA_DEV_SOLR_URL'] || "http://127.0.0.1:8983/solr/blacklight-core" %>
test: &test
  adapter: solr
  url: <%= ENV['YCBA_TEST_SOLR_URL'] || "http://127.0.0.1:8983/solr/blacklight-core" %>
production:
  adapter: solr
  url: <%= ENV['YCBA_PROD_SOLR_URL'] || "http://127.0.0.1:8983/solr/blacklight-core" %>
